Repository QC-UCI/qc-uci.club, pull requests merged in 2020-09, with the labels that each got.

#11 add Join page
  css/style.css
  index.html
  join.html
Labels: enhancement, good first issue, help wanted

#14 Contact Us
  contact_us.html
  css/style.css
  image/linkedin_icon.png
  image/mail_icon.png
  image/slack_icon.png
  index.html
Labels: HIGH

#12 add Events page
  .gitignore
  css/style.css
  event.html
  js/event.js
Labels: HIGH, enhancement

#10 add Team page
  css/style.css
  image/AhmadSebdani.jpg
  image/AndyPark.jpg
  image/ChrisChen.jpg
  image/KylerFrazier.jpeg
  image/OCH.jpg
  image/TonyTong.jpg
  image/ZhuHaochen.jpg
  js/team.js
  team.html
Labels: HIGH
